spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-dockerlesson:5432/dockerlessondb
    username: root
    password: haslo

  liquibase:
    contexts: prod
